package RedSocial;

public enum NotificacionesRedSocial {

    LIKE,
    SUBSCRIPCION,
    ARTISTASEDADEBAJA,
    ARTISTAPOSTEA,
    AGREGARSEGUIDOR,
    POSTALCANZALIKES,
    ARTISTAALCANZASUBSCRIPTORES

}
