/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import App.Accounts.AccountTypes;
import Messages.AuctionsInfo;
import Networking.ClientSide.Client;

import javax.swing.JOptionPane;
import java.awt.*;
import java.util.ArrayList;

/**
 *
 * @author Fernando Alvarez
 */
public class PantallaOferente extends javax.swing.JFrame implements SubastaFrame{

    /**
     * Creates new form PantallaOferente
     */
    private AuctionsInfo currentAuctionInfo;//Current subasta
    private final Client client;
    private ArrayList<AuctionsInfo> auctionsInfos;

    
    public PantallaOferente() {
        this.client = new Client("127.0.0.1", 7800, AccountTypes.BUYER, this);
        initComponents();
        //showNotification("Se actualizo el precio de la subasta #2");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnUnirse = new javax.swing.JButton();
        btnOfrecer = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDisplayInfo = new javax.swing.JTextArea();
        lblImagen = new javax.swing.JLabel();
        txtOfrecer = new javax.swing.JTextField();
        btnVerSubastas = new javax.swing.JButton();
        btnMisSubastas = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnUnirse.setText("Unirse");
        btnUnirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnirseActionPerformed(evt);
            }
        });

        btnOfrecer.setText("Ofrecer");
        btnOfrecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOfrecerActionPerformed(evt);
            }
        });

        txtDisplayInfo.setColumns(5);
        txtDisplayInfo.setRows(5);
        txtDisplayInfo.setEnabled(false);
        jScrollPane2.setViewportView(txtDisplayInfo);

        btnVerSubastas.setText("Ver Subastas");
        btnVerSubastas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerSubastasActionPerformed(evt);
            }
        });

        btnMisSubastas.setText("Mis Subastas");
        btnMisSubastas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMisSubastasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnUnirse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOfrecer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOfrecer, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVerSubastas)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMisSubastas)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMisSubastas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnUnirse)
                        .addComponent(btnOfrecer)
                        .addComponent(txtOfrecer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnVerSubastas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public ArrayList<AuctionsInfo> getAuctionsInfos() {
        return auctionsInfos;
    }

    public void setAuctionsInfos(ArrayList<AuctionsInfo> auctionsInfos) {
        this.auctionsInfos = auctionsInfos;
    }

    public static boolean isNumeric(String strNum) {
        if (strNum == null) {
            return false;
        }
        try {
            double d = Double.parseDouble(strNum);
        } catch (NumberFormatException nfe) {
            return false;
        }
        return true;
    }

    private void btnUnirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnirseActionPerformed
        //Se une a una subasta ahora puede ofrecer si quiere o no pero siemore  se le avisa si alguien gana
        //Parecido al follow de red social
        if(currentAuctionInfo !=null){
            client.subscribeToAuction(currentAuctionInfo.getId());
        }
    }//GEN-LAST:event_btnUnirseActionPerformed

    private void btnOfrecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOfrecerActionPerformed
        //Envia al servidor el monto ofrecido de la subasta seleccionada
        //Parecido al like pero enviando una cantidad
        String bid = txtOfrecer.getText();

        if(isNumeric(bid)){
            if(currentAuctionInfo !=null){
                client.addBid(bid, currentAuctionInfo.getId());
            } else {
                showNotification("Choose an Auction first");
            }
        } else {
            showNotification("Your bid is not numeric!");
        }


    }//GEN-LAST:event_btnOfrecerActionPerformed

    private void btnVerSubastasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerSubastasActionPerformed
        //Pide todas las subastas del servidor
        //Parecido al getNext pero recibe una lista
        client.getAllAuctions();

        try{Thread.sleep(1000);}catch (Exception e){ e.printStackTrace(); }

        PantallaSubastas ps = new PantallaSubastas(this,"Subastas");
        ps.setVisible(true);
    }//GEN-LAST:event_btnVerSubastasActionPerformed

    private void btnMisSubastasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMisSubastasActionPerformed
        //Pide todas las subastas del oferente
        //Parecido al getNext pero recibe una lista
        PantallaSubastas ps = new PantallaSubastas(this,"Mis Subastas");
        ps.setVisible(true);
    }//GEN-LAST:event_btnMisSubastasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMisSubastas;
    private javax.swing.JButton btnOfrecer;
    private javax.swing.JButton btnUnirse;
    private javax.swing.JButton btnVerSubastas;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JTextArea txtDisplayInfo;
    private javax.swing.JTextField txtOfrecer;
    // End of variables declaration//GEN-END:variables

    @Override
    public void showAuction(AuctionsInfo auctionsInfo) {
        this.currentAuctionInfo = auctionsInfo;
        this.txtDisplayInfo.setText(auctionsInfo.toString());
        this.txtDisplayInfo.setDisabledTextColor(Color.BLACK);
    }
    
    public void showNotification(String string){
        JOptionPane.showMessageDialog(this, string);
    }
}
