/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import App.Articulo;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Fernando Alvarez
 */
public class PantallaSubastas extends javax.swing.JFrame implements ListSelectionListener{

    
    ArrayList<InfoSubasta> subastas;
    SubastaFrame pantalla;
    
    public PantallaSubastas() {
        initComponents();
        subastas = new ArrayList<>();
        //Test
        Articulo a1 = new Articulo("Telfono", "xd", 1500);
        Articulo a3 = new Articulo("Telfono", "xd", 1200);
        Articulo a4 = new Articulo("Sombrero", "xd", 800);
        subastas.add(new InfoSubasta(a1,1500,"activo","Juan",2));
        subastas.add(new InfoSubasta(a4,4000,"activo","Fabian",3));
        subastas.add(new InfoSubasta(a3,2000,"activo","Marco",6));
        setListInfo();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    
    public PantallaSubastas(SubastaFrame pantalla,String tittle){
        initComponents();
        subastas = new ArrayList<>();
        this.pantalla = pantalla;
        this.setTitle(tittle);
                //Test
        Articulo a1 = new Articulo("Telfono", "xd", 1500);
        Articulo a3 = new Articulo("Telfono", "xd", 1200);
        Articulo a4 = new Articulo("Sombrero", "xd", 800);
        subastas.add(new InfoSubasta(a1,1500,"activo","Juan",2));
        subastas.add(new InfoSubasta(a4,4000,"activo","Fabian",3));
        subastas.add(new InfoSubasta(a3,2000,"activo","Marco",6));
        setListInfo();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listSubastas = new javax.swing.JList<>();
        lblText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(listSubastas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblText, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblText, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaSubastas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaSubastas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaSubastas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaSubastas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaSubastas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblText;
    private javax.swing.JList<String> listSubastas;
    // End of variables declaration//GEN-END:variables

    public void setListInfo(){
        String info[] = new String[subastas.size()];
        for (int i = 0;i<subastas.size();i++) {
            InfoSubasta subasta = subastas.get(i);
            info[i] = subasta.articulo.getNombre()+subasta.pujaMasAlta+"Subasta #"+subasta.idSubasta+"Estado: "+subasta.estado;
        }
            listSubastas.setListData(info);
            listSubastas.addListSelectionListener(this);
    }
    
    public void askForList(){
        //Llena la lista y se guarda el nombre y el id de todas las subastas
        //Llama el metodo selecionar
    }
    public void selectSubasta(int index){
        //Con los id guardados manda a llamar al servidor con el id selecionado
        //Y los datos recibidos los muestra en la pantalla principal
        pantalla.mostrarSubasta(subastas.get(index));
        System.out.println(index);
        System.out.println("Hola");
        dispose();
    }

    @Override
    public void valueChanged(ListSelectionEvent e) {
        if (!e.getValueIsAdjusting()) {            
            selectSubasta(listSubastas.getSelectedIndex());   
        }
    }

}
